---
title: 'Module "4": Assignment 1'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message = FALSE}
library(tidyverse)
library(vegan)
```

```{r message = FALSE}
insects <- read.csv("../data_raw/SCR_camera_data.csv")
```

```{r}
insects_sac <- specaccum(insects)
```

```{r}
insects_sac_fit <- fitspecaccum(insects_sac, model = "asymp")
```

3. 
```{r}
coef(insects_sac_fit)
```

4. 
```{r}
plot(insects_sac_fit)
```

```{r}
comm1 <- data.frame(species = c("DO", "DM", "SO", "SH", "SF", "PP", "PB", "BA"),
                   individuals = c(14, 89, 30, 12, 3, 3, 8, 23))
comm2 <- data.frame(species = c("DO", "DM", "SO", "SH", "SF"),
                   individuals = c(37, 32, 30, 44, 39))
```

6. 
```{r}
nrow(comm1)
nrow(comm2)
```


7. 
```{r}
N_comm1 <- sum(comm1$individuals)
N_comm1
```

8. 
```{r}
comm1$prop <- comm1$individuals / N_comm1
comm1
```

9. 
```{r}
comm1$ln_prop <- log(comm1$prop)
comm1
```

10. 
```{r}
comm1$prop_lnprop <- comm1$prop * comm1$ln_prop
comm1
```

11. 
```{r}
H_comm1 <- sum(comm1$prop_lnprop * -1)
H_comm1
```

12. 
```{r}
N_comm2 <- sum(comm2$individuals)
comm2$prop <- comm2$individuals / N_comm2
comm2$ln_prop <- log(comm2$prop)
comm2$prop_lnprop <- comm2$prop * comm2$ln_prop
H_comm2 <- sum(comm2$prop_lnprop * -1)
H_comm2
```


14. 
```{r}
comm1$prop_sq <- comm1$prop * comm1$prop
comm1
```

15. 
```{r}
D1 = 1 - sum(comm1$prop_sq)
D1
```

16. 
```{r}
comm2$prop_sq <- comm2$prop * comm2$prop
D2 = 1 - sum(comm2$prop_sq)
D2
```

