---
title: "Module 3 Assignment 2"
author: "Ellen Bledsoe"
date: "2022-10-18"
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message = FALSE}
library(tidyverse)
```

```{r}
N <- 1000
n <- 100
```

```{r}
N_A <- 200
N_B <- 500
N_C <- 300
```

```{r}
sd_A <- 9
sd_B <- 4
sd_C <- 7
```

```{r}
cost_A <- 1.5
cost_B <- 2
cost_C <- 4
```


5.  

```{r}
opt_allo_A <- N_A * sd_A / sqrt(cost_A)
opt_allo_B <- N_B * sd_B / sqrt(cost_B)
opt_allo_C <- N_C * sd_C / sqrt(cost_C)

opt_allo_A
opt_allo_B
opt_allo_C
```

6.  

```{r}
opt_allo_total <- opt_allo_A + opt_allo_B + opt_allo_C
opt_allo_total
```

7.  

```{r}
n_A <- n * (opt_allo_A / opt_allo_total) # 37
n_A <- round(n_A)
# OR #
n_B <- round(n * (opt_allo_B / opt_allo_total)) # 36
n_C <- round(n * (opt_allo_C / opt_allo_total)) # 27

n_A
n_B
n_C
```

9.  

```{r}
grasshoppers <- read_csv("../data_raw/grasshoppers.csv")
as_tibble(grasshoppers)
```


    ```{r echo = FALSE, include = FALSE}
    grasshoppers %>% 
      group_by(stratum) %>% 
      count(stratum)
    ```

    ```{r}
    stratumA <- grasshoppers %>% filter(stratum == "A")
    stratumB <- grasshoppers %>% filter(stratum == "B")
    stratumC <- grasshoppers %>% filter(stratum == "C")
    ```

13. 

    a.

    ```{r}
    # take the mean of the `abund` column
    mean_A <- mean(stratumA$abund)
    mean_A
    mean_B <- mean(stratumB$abund)
    mean_B
    mean_C <- mean(stratumC$abund)
    mean_C
    ```

    b.  

    ```{r}
    tau_hat_A <- N_A * mean_A
    tau_hat_A
    tau_hat_B <- N_B * mean_B
    tau_hat_B
    tau_hat_C <- N_C * mean_C
    tau_hat_C
    ```

    c.  

    ```{r}
    # similar to (a) but calculating the variance instead of the mean
    var_A <- var(stratumA$abund)
    var_A
    var_B <- var(stratumB$abund)
    var_B
    var_C <- var(stratumC$abund)
    var_C
    ```


14. 

    a.  

    ```{r}
    # pop corrections
    pop_correction_A <- (N_A-n_A)/N_A
    pop_correction_A
    pop_correction_B <- (N_B-n_B)/N_B
    pop_correction_B
    pop_correction_C <- (N_C-n_C)/N_C
    pop_correction_C

    # var_y_bars 
    var_y_bar_A <- pop_correction_A * (var_A / n_A)
    var_y_bar_A
    var_y_bar_B <- pop_correction_B * (var_B / n_B)
    var_y_bar_B
    var_y_bar_C <- pop_correction_C * (var_C / n_C)
    var_y_bar_C
    ```

    b.  

    ```{r}
    var_tau_hat_A <- N_A^2 * var_y_bar_A
    var_tau_hat_A
    var_tau_hat_B <- N_B^2 * var_y_bar_B
    var_tau_hat_B
    var_tau_hat_C <- N_C^2 * var_y_bar_C
    var_tau_hat_C
    
    ```


15. 

    a.  

    ```{r}
    tau_hat <- tau_hat_A + tau_hat_B + tau_hat_C
    tau_hat
    ```

    b.  

    ```{r}
    var_tau_hat <- var_tau_hat_A + var_tau_hat_B + var_tau_hat_C
    var_tau_hat
    ```

16. 

    a.  

    ```{r}
    y_bar <- tau_hat / N
    y_bar
    ```

    b.  

    ```{r}
    var_y_bar <- var_tau_hat / N^2
    var_y_bar
    ```

