---
title: "Module 1, Assignment 3"
author: ""            # <- your name here!
date: '2023-02-13'    # <- you can change the date if you want
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

5.  

```{r}
library(tidyverse)
```

### 

```{r message = FALSE}
pads <- read_csv("../data_raw/CactusPads_joined.csv")
```

8.  

```{r}
pads %>% 
  select(length_in, width_in, depth_in, species)
# OR select(pads, length_in, width_in, depth_in, species)
```

9.  

```{r}
pads %>% 
  filter(depth_in > 1)
# OR filter(pads, depth_in > 1)
```

11. 

```{r}
mutate(pads, length_cm = length_in * 2.54) %>% 
  select(length_in, length_cm)
```

12. 

```{r}
pads %>% 
  summarise(mean_width = mean(width_in),
            sd_width = sd(width_in))
```

13. 

```{r}
pads_volume <- pads %>% 
  mutate(volume_in3 = length_in * width_in * depth_in)
pads_volume
```

14. 

```{r}
pads_volume %>% 
  group_by(species) %>% 
  summarize(mean_volume = mean(volume_in3),
           sd_volume = sd(volume_in3))
```

16. 

```{r}
pads_volume %>% 
  group_by(species) %>% 
  summarize(mean_volume = mean(volume_in3),
           sd_volume = sd(volume_in3)) %>% 
  mutate(CV = sd_volume / mean_volume * 100)
```
