---
title: "Module 3 Assignment 1"
author: "Ellen Bledsoe"
date: "2023-04-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(unmarked) 
```


```{r}
javelina <- read_csv("../data_raw/javelina.csv")
coyote <- read_csv("../data_raw/coyote.csv")
```
1. 
```{r}
num_detections <- rowSums(javelina)
sites_surveyed <- nrow(javelina)
sites_detection <- length(num_detections[num_detections > 0])
naive_occupancy <- sites_detection / sites_surveyed
naive_occupancy
```

3.
```{r}
# create the data frame with 40 rows and each column with the survey number
javelina_survey_time <- tibble(.rows = 40,
                            time_1 = "1",
                            time_2 = "2",
                            time_3 = "3",
                            time_4 = "4",
                            time_5 = "5")

# make this into a list of one dataframe
javelina_survey_time <- list(time = javelina_survey_time)
```


4.
```{r}
javelinaUMF <- unmarkedFrameOccu(javelina, obsCovs = javelina_survey_time)
head(javelinaUMF) # check out the data
```


5.
```{r}
javelina_pdot_psidot <- occu(~1 ~1, data = javelinaUMF)
```

6.
```{r}
javelina_ptime_psidot <- occu(~time-1 ~1, data = javelinaUMF)
```


7.
```{r}
javelina_models <- fitList(javelina_pdot_psidot  = javelina_pdot_psidot, 
                        javelina_ptime_psidot = javelina_ptime_psidot)
modSel(javelina_models)
```


9.
```{r}
plogis(coef(javelina_pdot_psidot))  # estimates of psi and p
plogis(confint(javelina_pdot_psidot, type = "det", level = 0.95))
```
10.
```{r}
plogis(coef(javelina_pdot_psidot))  # estimates of psi and p
plogis(confint(javelina_pdot_psidot, type = "state", level = 0.95))
```



12. 

```{r}
num_detections <- rowSums(coyote)
sites_surveyed <- nrow(coyote)
sites_detection <- length(num_detections[num_detections > 0])
naive_occupancy <- sites_detection / sites_surveyed
naive_occupancy
```


13. 

```{r}
# create the data frame with 20 rows and each column with the survey number
coyote_survey_time <- tibble(.rows = 40,
                            time_1 = "1",
                            time_2 = "2",
                            time_3 = "3",
                            time_4 = "4",
                            time_5 = "5")

# make this into a list of one dataframe
coyote_survey_time <- list(time = coyote_survey_time)
```

14. 

```{r}
coyoteUMF <- unmarkedFrameOccu(coyote, obsCovs = coyote_survey_time)
head(coyoteUMF) # check out the data
```

15. 
```{r}
coyote_pdot_psidot <- occu(~1 ~1, data = coyoteUMF)
coyote_ptime_psidot <- occu(~time-1 ~1, data = coyoteUMF)
```


16. 

```{r}
coyote_models <- fitList(coyote_pdot_psidot  = coyote_pdot_psidot, 
                          coyote_ptime_psidot = coyote_ptime_psidot)
modSel(coyote_models)
```

17. 

```{r}
plogis(coef(coyote_pdot_psidot))  # estimates of psi and p
plogis(confint(coyote_pdot_psidot, type = "det", level = 0.95))
plogis(confint(coyote_pdot_psidot, type = "state", level = 0.95))
```

