---
title: "Module 2, Assigment 1"
author: "Ellen Bledsoe" # <- your name here
date: '2022-09-19'      # <- current date here
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

5.  

```{r}
heights <- c(63, 69, 60, 65, NA, 68, 61, 70, 61, 59, 64, 69, 63, 63, NA, 72, 65, 64, 70, 63, 65)
```

```{r}
mean(heights)
```

6.  

```{r}
mean(heights, na.rm = TRUE)
```

7.  
```{r}
heights[6:10]
```

8.  

```{r}
rhymes <- c("cat", "rat", "bat", "hat")
rhymes
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
# read in the cactus pads data
pads <- read_csv("../data_raw/CactusPadsData.csv") 

# read in the cactus data and choose only the group_id, species, and size columns
cactus <- read_csv("../data_raw/CactusData.csv") %>% select(group_id, species, size)

# join the two datasets together using the group_id column
# this matches up the cactus species and size for each cactus pad (row) with the same group_id
pads <- right_join(pads, cactus, by = "group_id")

# remove the cactus data frame because we don't need it anymore (and it might be confusing)
rm(cactus)
```


10. 

```{r}
head(pads)
```

11. 

```{r}
mean(pads$depth_in)
```

12. 

```{r}
round(mean(pads$depth_in), digits = 1)
```

13. 

```{r}
hist(pads$width_in)
```


16. 
```{r}
ficus <- pads[pads$species == "Opuntia ficus-indica", ]
ficus
santa_rita <- pads[pads$species == "Opuntia santa-rita", ]
santa_rita
```

17.

```{r}
mean_ficus <- mean(ficus$length_in)
mean_ficus
mean_santa <- mean(santa_rita$length_in)
mean_santa
```

18. 

```{r}
sd_ficus <- sd(ficus$length_in)
sd_ficus
sd_santa <- sd(santa_rita$length_in)
sd_santa
```

19.

```{r}
cv_ficus <- (sd_ficus / mean_ficus) * 100
cv_ficus
cv_santa <- (sd_santa / mean_santa) * 100
cv_santa
```

