---
title: "Module 1 Assignment 2"
author: "Ellen Bledsoe"     # <- your name inside quotes here!
date: "`r Sys.Date()`"      # <- this will produce today's date, so you can leave it
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

5.  

```{r}
birds <- 121
birds
```

6.  

```{r}
fewer_birds <- 121^(0.5)
fewer_birds
```

7.  

```{r}
snails <- c(7, 2, 19, 4, 0, 2)
snails
```

8.  

```{r}
class(snails)
```



10. 

```{r}
rhymes <- c("cat", "rat", "bat", "hat")
rhymes
```


```{r}
cactus <- read.csv("../data_raw/AllCactusData.csv")
```

```{r}
pad_length <- cactus$length_in
```

```{r}
pad_width <- cactus$width_in
damage <- cactus$damage
```

11. 

```{r}
pad_width[4]
```

12. 

```{r}
answer <- pad_width[42]
answer
```

12. 

```{r}
pad_width[6:10]
```

13. 

```{r}
length(damage)
```

14. 

```{r}
damage[damage == "None"]
```

15. 
```{r}
length(damage[damage == "None"])
```


17. 

```{r}
pad_length[pad_length > 5]
```

18. 

```{r}
mean(pad_length)
sd(pad_length)
```

19. 

```{r}
mean(pad_width)
sd(pad_width)
```
